# Generated by Django 3.2.3 on 2023-07-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_favorite_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Рецепт в списке покупок', 'verbose_name_plural': 'Рецепты в списке покупок'},
        ),
    ]
